services:

  # Build app from Dockerfile in same folder
  app:
    build: db/.                # Uses db/Dockerfile
    depends_on:
      db:
        condition: service_healthy

  # Build the db as name world from the Dockerfile in the db folder
  # exposing the port if we want to run code outside a container
  db:
    build: db/.
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=world
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10